"""``EvidenceClassificationReconciliationCursor`` — the durable,
per-activation-boundary scan cursor
``services.evidence.classification_job.reconcile_missing_classification_jobs``
uses to walk evidence forward in REGISTRATION (``created_at``) order
without ever re-scanning a row it has already inspected (BAGMAN
accounting platform, `evidence/automatic-classification-activation`
WO — post-merge preflight review correction, item B).

Mirrors ``services.mailbox.cursor``'s own docstring/style conventions
closely — read that module first if anything here is unclear on a
point it already established. Not a JSON-Schema-contract-backed domain
object, for the same reason ``MailboxFolderCursor`` is not one (see
that module's own docstring): this is internal reconciliation
plumbing, never surfaced through a GET endpoint, never displayed in the
GUI, never referenced by another canonical object.

The starvation bug this closes
------------------------------------------------------------------------
Before this module existed, ``reconcile_missing_classification_jobs``
paged via ``evidence_repository.list_evidence(received_at_from=...,
limit=page_size, offset=offset)``, ordered (the repository's fixed
default) ``received_at DESC, evidence_id DESC``, always restarting at
``offset=0`` on every call, with no persisted state carried between
calls. If more than ``max_rows_scanned`` already-resolved evidence rows
sorted ahead of a genuinely orphaned row in that fixed ordering, the
orphan could never be reached by any number of repeated calls — every
call re-scanned exactly the same window and stopped there. Worse,
because the ordering was ``received_at DESC`` while new evidence kept
arriving with ever-more-recent ``received_at`` values, an orphan's
position in that ordering only ever got WORSE over time: a permanent,
unrecoverable starvation, not merely a slow-convergence issue.

The fix requires two things together, neither sufficient alone:

1. Scan in REGISTRATION order (``created_at ASC, evidence_id ASC`` —
   see ``EvidenceRepository.list_evidence``'s own new
   ``order_by_created_at`` parameter), which is the only ordering under
   which an orphan's position is FIXED forever once it exists (new
   evidence only ever appends after it in this ordering, never in
   front of it).
2. Persist a durable cursor recording how far a previous call already
   scanned, so the NEXT call starts exactly where the last one left
   off, rather than restarting at the front of the window every time.

Together, these guarantee genuine, monotonic, PERMANENT forward
progress with a FIXED ``max_rows_scanned`` regardless of how large the
resolved-evidence corpus grows — the property a single-fixed-window
scan (in either ordering) can never provide on its own.

Why ``cursor_key`` is ``activation_boundary.isoformat()``, not a
constant
------------------------------------------------------------------------
``reconcile_missing_classification_jobs`` calls this repository with
``cursor_key = activation_boundary.isoformat()`` — a deliberate,
documented design choice, not an oversight. If an operator ever
corrects a misconfigured activation boundary (e.g. it was set to the
wrong date and is later fixed), the NEW boundary value naturally gets
its own fresh cursor, starting the scan over from that new boundary,
rather than silently carrying forward a stale scan position that no
longer corresponds to the newly-configured value. A cursor keyed on a
constant would instead resume from wherever the OLD boundary's scan
had reached — silently wrong the moment the boundary itself changes.

Why the tie-break is SET membership (``last_evidence_ids``), never a
single scalar compared with ``<=``
------------------------------------------------------------------------
Post-merge audit correction (independently verified against
``core.identity.generate_id``'s own docstring): an earlier version of
this cursor stored a single scalar ``last_evidence_id`` and
``reconcile_missing_classification_jobs`` skipped any row sharing the
cursor's exact ``last_created_at`` whose ``evidence_id <=
last_evidence_id``. That is an ORDERING assumption — it silently
assumes any row sharing that timestamp and not yet inspected must sort
AFTER every row already inspected. ``evidence_id`` is a UUIDv7
(``core.identity.generate_id``), and that module's own docstring is
explicit that its monotonic-counter guarantee ("later-generated sorts
later") holds only WITHIN one process — it says nothing about, and
cannot guarantee anything about, ordering between ids generated by two
DIFFERENT OS processes (BAGMAN registers evidence from at least two:
the API server and the mailbox-ingestion worker). If two evidence rows
registered by different processes happen to share the exact same
microsecond-precision ``created_at``, there is no guarantee the
later-registered row's id sorts after the earlier one's. Under the old
scalar ``<=`` scheme, if it happened to sort BEFORE, the row would be
silently and PERMANENTLY skipped forever — either invisible at that
cursor position, or (once the cursor's watermark later advances past
that timestamp) excluded from every future scan's ``created_at_from``
filter too, with no error and no log.

The fix: ``last_evidence_ids`` is the SET of every ``evidence_id``
actually inspected by any past call whose ``created_at`` was exactly
``last_created_at``. The skip condition this cursor exists to support
is pure set membership ("has this exact id already been inspected at
this exact timestamp?"), never an ordering comparison — so it is
correct regardless of what any two ids sharing a timestamp happen to
compare as strings, cross-process or not.
"""
from __future__ import annotations

import abc
import threading as _threading
from dataclasses import dataclass
from datetime import datetime
from typing import Collection, Optional

from core.timestamps import utc_now


@dataclass(frozen=True)
class EvidenceClassificationReconciliationCursor:
    #: Caller-chosen key — in practice always
    #: ``activation_boundary.isoformat()`` (see module docstring's own
    #: "Why cursor_key is activation_boundary.isoformat()" section).
    cursor_key: str
    #: The ``created_at`` of the highest-ordered evidence row actually
    #: INSPECTED (never merely cursor-skipped) by the scan so far.
    last_created_at: datetime
    #: EVERY ``evidence_id`` actually inspected (never merely
    #: cursor-skipped) by any past call whose ``created_at`` was
    #: exactly ``last_created_at`` — a set-membership tie-break, never
    #: an ordering comparison (see module docstring's own "Why the
    #: tie-break is SET membership" section for why: cross-process
    #: UUIDv7 ordering is not guaranteed). A sorted tuple for a
    #: deterministic, hashable value on this frozen dataclass.
    last_evidence_ids: tuple[str, ...]
    created_at: datetime
    updated_at: datetime


class EvidenceClassificationReconciliationCursorRepository(abc.ABC):
    @abc.abstractmethod
    def get_cursor(self, cursor_key: str) -> Optional[EvidenceClassificationReconciliationCursor]:
        """`None` if no cursor has ever been advanced for `cursor_key`
        yet — an ordinary, expected state for a fresh activation
        boundary's very first reconciliation call."""
        raise NotImplementedError

    @abc.abstractmethod
    def advance_cursor(
        self, cursor_key: str, *, last_created_at: datetime, last_evidence_ids: Collection[str]
    ) -> EvidenceClassificationReconciliationCursor:
        """UPSERT: creates the row if it does not exist yet for
        `cursor_key`, replaces `last_created_at`/`last_evidence_ids`/
        `updated_at` if it does — no separate bootstrap step is needed
        (unlike `services.mailbox.cursor.MailboxFolderCursor`, there is
        nothing else on this cursor that needs preserving across its
        first creation). `last_evidence_ids` must already be the FULL,
        final set of ids inspected at `last_created_at` (the union of
        any prior call's ids at that same timestamp plus whatever was
        newly inspected this call, when the watermark did not move past
        it) — this repository never merges/unions itself, it only
        stores verbatim what the caller passes."""
        raise NotImplementedError


class InMemoryEvidenceClassificationReconciliationCursorRepository(
    EvidenceClassificationReconciliationCursorRepository
):
    """Narrow in-memory reference implementation. `RLock`-guarded,
    mirroring every other in-memory repository in this codebase that
    may see genuine concurrent HTTP-driven callers within one process
    (e.g. `services.evidence.classification_job
    .InMemoryEvidenceClassificationJobRepository`)."""

    def __init__(self) -> None:
        self._by_key: dict[str, EvidenceClassificationReconciliationCursor] = {}
        self._lock = _threading.RLock()

    def get_cursor(self, cursor_key: str) -> Optional[EvidenceClassificationReconciliationCursor]:
        with self._lock:
            return self._by_key.get(cursor_key)

    def advance_cursor(
        self, cursor_key: str, *, last_created_at: datetime, last_evidence_ids: Collection[str]
    ) -> EvidenceClassificationReconciliationCursor:
        with self._lock:
            now = utc_now()
            existing = self._by_key.get(cursor_key)
            updated = EvidenceClassificationReconciliationCursor(
                cursor_key=cursor_key,
                last_created_at=last_created_at,
                last_evidence_ids=tuple(sorted(last_evidence_ids)),
                created_at=existing.created_at if existing is not None else now,
                updated_at=now,
            )
            self._by_key[cursor_key] = updated
            return updated
