"""``EvidenceClassificationReconciliationCursor`` — the durable,
per-activation-boundary scan cursor
``services.evidence.classification_job.reconcile_missing_classification_jobs``
uses to walk evidence forward in REGISTRATION (``created_at``) order
without ever re-scanning a row it has already inspected (BAGMAN
accounting platform, `evidence/automatic-classification-activation`
WO — post-merge preflight review correction, item B).

Mirrors ``services.mailbox.cursor``'s own docstring/style conventions
closely — read that module first if anything here is unclear on a
point it already established. Not a JSON-Schema-contract-backed domain
object, for the same reason ``MailboxFolderCursor`` is not one (see
that module's own docstring): this is internal reconciliation
plumbing, never surfaced through a GET endpoint, never displayed in the
GUI, never referenced by another canonical object.

The starvation bug this closes
------------------------------------------------------------------------
Before this module existed, ``reconcile_missing_classification_jobs``
paged via ``evidence_repository.list_evidence(received_at_from=...,
limit=page_size, offset=offset)``, ordered (the repository's fixed
default) ``received_at DESC, evidence_id DESC``, always restarting at
``offset=0`` on every call, with no persisted state carried between
calls. If more than ``max_rows_scanned`` already-resolved evidence rows
sorted ahead of a genuinely orphaned row in that fixed ordering, the
orphan could never be reached by any number of repeated calls — every
call re-scanned exactly the same window and stopped there. Worse,
because the ordering was ``received_at DESC`` while new evidence kept
arriving with ever-more-recent ``received_at`` values, an orphan's
position in that ordering only ever got WORSE over time: a permanent,
unrecoverable starvation, not merely a slow-convergence issue.

The fix requires two things together, neither sufficient alone:

1. Scan in REGISTRATION order (``created_at ASC, evidence_id ASC`` —
   see ``EvidenceRepository.list_evidence``'s own new
   ``order_by_created_at`` parameter), which is the only ordering under
   which an orphan's position is FIXED forever once it exists (new
   evidence only ever appends after it in this ordering, never in
   front of it).
2. Persist a durable cursor recording how far a previous call already
   scanned, so the NEXT call starts exactly where the last one left
   off, rather than restarting at the front of the window every time.

Together, these guarantee genuine, monotonic, PERMANENT forward
progress with a FIXED ``max_rows_scanned`` regardless of how large the
resolved-evidence corpus grows — the property a single-fixed-window
scan (in either ordering) can never provide on its own.

Why ``cursor_key`` is ``activation_boundary.isoformat()``, not a
constant
------------------------------------------------------------------------
``reconcile_missing_classification_jobs`` calls this repository with
``cursor_key = activation_boundary.isoformat()`` — a deliberate,
documented design choice, not an oversight. If an operator ever
corrects a misconfigured activation boundary (e.g. it was set to the
wrong date and is later fixed), the NEW boundary value naturally gets
its own fresh cursor, starting the scan over from that new boundary,
rather than silently carrying forward a stale scan position that no
longer corresponds to the newly-configured value. A cursor keyed on a
constant would instead resume from wherever the OLD boundary's scan
had reached — silently wrong the moment the boundary itself changes.

Why the tie-break is SET membership (``last_evidence_ids``), never a
single scalar compared with ``<=``
------------------------------------------------------------------------
Post-merge audit correction (independently verified against
``core.identity.generate_id``'s own docstring): an earlier version of
this cursor stored a single scalar ``last_evidence_id`` and
``reconcile_missing_classification_jobs`` skipped any row sharing the
cursor's exact ``last_created_at`` whose ``evidence_id <=
last_evidence_id``. That is an ORDERING assumption — it silently
assumes any row sharing that timestamp and not yet inspected must sort
AFTER every row already inspected. ``evidence_id`` is a UUIDv7
(``core.identity.generate_id``), and that module's own docstring is
explicit that its monotonic-counter guarantee ("later-generated sorts
later") holds only WITHIN one process — it says nothing about, and
cannot guarantee anything about, ordering between ids generated by two
DIFFERENT OS processes (BAGMAN registers evidence from at least two:
the API server and the mailbox-ingestion worker). If two evidence rows
registered by different processes happen to share the exact same
microsecond-precision ``created_at``, there is no guarantee the
later-registered row's id sorts after the earlier one's. Under the old
scalar ``<=`` scheme, if it happened to sort BEFORE, the row would be
silently and PERMANENTLY skipped forever — either invisible at that
cursor position, or (once the cursor's watermark later advances past
that timestamp) excluded from every future scan's ``created_at_from``
filter too, with no error and no log.

The fix: ``last_evidence_ids`` is the SET of every ``evidence_id``
actually inspected by any past call whose ``created_at`` was exactly
``last_created_at``. The skip condition this cursor exists to support
is pure set membership ("has this exact id already been inspected at
this exact timestamp?"), never an ordering comparison — so it is
correct regardless of what any two ids sharing a timestamp happen to
compare as strings, cross-process or not.

Why ``advance_cursor`` merges instead of overwrites (evidence/
classification-activation-preflight WO, this round)
------------------------------------------------------------------------
An earlier version of ``advance_cursor`` unconditionally overwrote
whatever was persisted for ``cursor_key`` with the caller's own
proposed ``(last_created_at, last_evidence_ids)`` — correct for a
single writer, but unsafe once two ``reconcile_missing_classification_jobs``
calls for the SAME ``cursor_key`` can genuinely run concurrently (two
worker processes reconciling the same ``activation_boundary`` at the
same time, or — this round's addition — the forward cursor and the
"safety sweep" cursor both being written by the same call, or the
sweep cursor being written across successive laps). A caller's
proposed watermark is always computed from a scan that started from
whatever the cursor looked like at the START of that call's own
``get_cursor`` read; by the time it finishes scanning and calls
``advance_cursor``, another, faster-or-earlier-starting caller may
have ALREADY advanced the SAME cursor_key further in the meantime. If
``advance_cursor`` still blindly overwrote at that point, the slower
caller would silently REGRESS the persisted cursor backward — throwing
away real progress another caller already made, and potentially
losing part of the persisted ``last_evidence_ids`` set along with it.

The fix: the merge decision happens INSIDE the same row lock
(``SELECT ... FOR UPDATE`` in the Postgres implementation; the
in-memory implementation's own ``RLock``) that already existed to
serialize concurrent writers, comparing the caller's PROPOSED
``last_created_at`` against whatever is CURRENTLY persisted at write
time, not against whatever the caller itself last read:

* No existing row for ``cursor_key`` yet -> insert the proposal as-is
  (nothing to merge against).
* Proposed ``last_created_at`` STRICTLY GREATER than what is
  persisted -> this caller made genuinely more progress; replace both
  fields with the caller's own (the old timestamp's id set is
  irrelevant to any future scan once the watermark has moved past it —
  same reasoning :func:`reconcile_missing_classification_jobs` already
  applies to its own in-call ``running_ids`` tracking).
* Proposed ``last_created_at`` EQUAL to what is persisted -> UNION the
  two ``last_evidence_ids`` sets (never replace, never drop either
  side) — two callers independently inspected the same exact timestamp.
* Proposed ``last_created_at`` STRICTLY LESS than what is persisted ->
  a faster-or-earlier-starting caller already advanced the cursor
  further than this caller's own scan reached; NO-OP — return the
  EXISTING, more-advanced row completely unchanged (not even
  ``updated_at`` is bumped). This caller's own scan work is never
  lost: whatever jobs it found missing were already submitted
  idempotently (the real ``evidence_id`` unique constraint, exactly as
  always) DURING the scan, before this write was ever attempted — only
  the durable WATERMARK declines to move backward.

:func:`_resolve_cursor_advance` below is the one, pure, shared decision
function both concrete repositories call from inside their own lock —
"one shared code path", so the two implementations can never silently
drift apart on what counts as forward progress. It is intentionally
ignorant of WHY a proposal came in lower than what is persisted (a
genuine concurrent race, vs. this same module's own "safety sweep"
cursor deliberately restarting a new lap at ``activation_boundary``
once it has fully caught up to the forward cursor — see
:func:`services.evidence.classification_job.reconcile_missing_classification_jobs`'s
own docstring) — both cases are handled identically and correctly by
the same rule: a write that does not represent forward progress from
the CURRENTLY persisted state never regresses it, and the scan's own
job-submission side effects are never contingent on the cursor write
actually landing.

``lap`` — a second, independent ordering dimension (evidence/
classification-activation-preflight WO, this round's own permanent-
stall correction)
------------------------------------------------------------------------
The single-dimension ``created_at`` merge rule above, by itself, has a
genuine, blocking defect once a cursor is reused across multiple
DISTINCT "laps" the way the sweep cursor deliberately is (see
:func:`services.evidence.classification_job.reconcile_missing_classification_jobs`'s
own docstring for the full "safety sweep" mechanism): once one full lap
has completed (the sweep cursor's watermark sits at the OLD lap's final,
much-later position) and a NEW lap starts back at ``activation_boundary``,
that new lap's own FIRST bounded call can only make it partway through
the full window before ``sweep_max_rows_scanned`` cuts it off — so its own
proposed ``last_created_at`` is some early position, strictly LESS than
the OLD lap's much-further-along persisted watermark. Under the plain
``created_at`` comparison alone, that is indistinguishable from "a
slower/stale-started caller of the SAME lap lost a race" and is
therefore rejected as a regression — forever, on every subsequent call,
because the persisted watermark never actually moves, so every restart
attempt keeps re-proposing the same early, rejected position. Any
evidence in the unswept remainder of that window (exactly the case the
sweep exists to catch) is then never found, permanently — independently
confirmed by both an external audit and a direct reproduction (seed a
completed lap whose window exceeds the sweep's own bounded budget,
insert an orphan beyond that budget, and observe the sweep cursor never
move and the orphan never get found across repeated calls — see
``tests/persistence/test_evidence_classification_job_reconciliation_sweep.py``'s
own bug-reproduction test).

The fix is ``lap``: a monotonically non-decreasing generation counter,
carried on the cursor itself, that is compared BEFORE ``created_at`` —
lexicographic ``(lap, created_at)`` ordering, never plain ``created_at``
ordering alone. A genuinely NEWER lap (higher ``lap``) always supersedes
an OLDER lap's position entirely, regardless of where its own first,
still-partial write happens to land relative to the old lap's much
further-along ``created_at`` — because the two are no longer compared
against each other at all once ``lap`` differs. Meaningful for BOTH
cursor keys (forward and sweep): the forward cursor never itself
increments it (it always proposes its own current ``lap`` value back
unchanged — a non-event dimension for that cursor, staying ``0`` for its
whole lifetime unless something else ever needs it); only the sweep
cursor's own "start a new lap" decision ever proposes a strictly higher
value than what is currently persisted.

:func:`_resolve_cursor_advance`'s rule, precisely:

* No existing row -> insert the proposal as-is (``lap`` as given by the
  caller — both the forward cursor and a sweep cursor's very first-ever
  call propose ``lap=0``).
* Proposed ``lap`` STRICTLY GREATER than existing ``lap`` -> accept the
  proposal's ``(lap, last_created_at, last_evidence_ids)`` WHOLESALE,
  unconditionally — this is the actual fix: a fresh lap's very first,
  still-partial write is no longer compared against the old lap's much
  further-along position at all.
* Proposed ``lap`` EQUAL to existing ``lap`` -> fall through to EXACTLY
  the existing ``created_at``-based comparison above (greater replaces;
  equal unions ``last_evidence_ids``; less is a no-op) — completely
  unchanged, still safe under concurrent same-lap writers.
* Proposed ``lap`` STRICTLY LESS than existing ``lap`` -> NO-OP, exactly
  mirroring the existing "less" case on the ``created_at`` dimension — a
  stale caller proposing an older lap generation than what is already
  persisted never regresses the lap counter either.

Why this remains safe under genuine concurrency (the same "two workers
race on this exact cursor_key" scenario the module docstring above
already establishes safety for on the ``created_at`` dimension alone):
if two callers BOTH independently decide "time to start lap N+1" for the
SAME ``cursor_key`` at the same time (both having read the same old
``lap=N`` cursor), whichever one's write lands first, inside the row
lock, sets ``lap=N+1`` at whatever partial position it reached (the
"proposed.lap > existing.lap" branch — unconditional acceptance). The
SECOND writer's own proposal — also ``lap=N+1``, computed from its own,
independent scan — then finds ``proposed.lap == existing.lap`` when it
takes the lock, and falls into the ORDINARY, already-safe
``created_at``/``last_evidence_ids`` merge against the first writer's
result. No special-casing is needed: the SAME merge function handles
both "someone already started this lap" and "I am the very first to
start this lap" identically and correctly, once ``lap`` is part of the
comparison — exactly the same "compare against whatever is CURRENTLY
persisted at write time, inside the same lock" discipline the
``created_at`` dimension already relies on, just applied one dimension
higher first.

``target`` — freezing each lap's own upper bound at the moment it
starts (evidence/classification-activation-preflight WO, this round's
own final lap-boundary-liveness correction)
------------------------------------------------------------------------
``lap`` (above) fixes the permanent-STALL class of bug — a new lap's
own first, partial write can now always land. It does NOT, by itself,
fix a second, independent liveness gap: ``services.evidence
.classification_job.reconcile_missing_classification_jobs``'s sweep
section used to decide "has the current lap finished" by comparing the
persisted sweep cursor's own ``last_created_at`` against a FRESHLY
RE-READ forward-cursor frontier on every single call, and used that
same freshly-re-read frontier as the scan's own upper bound
(``created_at_to``) for the lap in progress. If new evidence keeps
arriving and advancing the forward cursor faster than the sweep's own
bounded per-call budget can make progress, that freshly-read frontier
keeps growing out from under the lap — the lap's own completion
condition (``last_created_at >= forward_frontier``) can then never be
satisfied, the lap never completes, a new lap never starts, and a row
that commits late, behind the sweep's current in-lap scan position,
can remain undiscovered indefinitely, as long as forward growth keeps
outpacing the sweep. An earlier version of both this module's and that
function's own docstrings framed "always use the freshest frontier" as
the CORRECT, intended design ("the sweep's own upper bound must
reflect the MOST current forward position, never a stale pre-call
snapshot") — that framing was itself the bug, not a feature, and is
retracted here.

The fix: ``EvidenceClassificationReconciliationCursor`` carries a
third persisted field, ``target`` — the IMMUTABLE upper bound
(``created_at`` value) for the CURRENT lap generation, established
EXACTLY ONCE, at the moment a NEW lap is proposed (exactly when the
caller proposes ``lap = existing.lap + 1``): the caller snapshots
whatever the forward frontier currently is AT THAT MOMENT and proposes
it as ``target`` alongside the new ``lap`` value. Every subsequent
call that CONTINUES that same lap (proposes the SAME ``lap`` back)
must reuse whatever ``target`` is ALREADY persisted for that lap —
never recompute or re-propose a fresh one from whatever the forward
frontier has grown to by then. The lap's own completion decision
becomes purely internal to the cursor itself:
``existing_sweep_cursor.last_created_at >=
existing_sweep_cursor.target`` — never compared against a freshly
re-read forward frontier at all. Only once that is true (the lap is
genuinely finished) does a NEW lap get started, snapshotting the
forward frontier ONE more time for the NEW lap's own frozen target.

Meaningful for the sweep cursor only, exactly like ``lap`` is
meaningful for the sweep cursor only: the forward cursor also carries
this field (schema uniformity — one shared dataclass/table for both
cursor keys, same as ``lap``), but never meaningfully uses it; it
always proposes its own currently-persisted ``target`` value back
unchanged, a permanent non-event for that cursor, mirroring exactly
how the forward cursor already treats ``lap``.

:func:`_resolve_cursor_advance`'s rule for ``target``, precisely —
enforced by the merge function ITSELF, as an invariant, never merely
relied upon from callers behaving correctly (the "concurrent-writer
semantics" requirement: two callers can each independently decide
"start lap N+1" and each snapshot a DIFFERENT forward-frontier value
at slightly different moments; only whichever write actually lands
FIRST, inside the row lock, may establish ``target`` for that lap
generation):

* No existing row -> insert the proposal's ``target`` as given
  (nothing to merge against — both the forward cursor's and a sweep
  cursor's very first-ever call propose whatever single value they
  have; see above for the forward cursor's own non-meaningful initial
  value).
* Proposed ``lap`` STRICTLY GREATER than existing ``lap`` -> ``target``
  is accepted WHOLESALE, as part of the exact same "accept the
  proposal's `(lap, last_created_at, last_evidence_ids)` wholesale"
  bundle the "lap" section above already documents — this is the ONE
  path by which a new ``target`` value may ever be introduced.
* Proposed ``lap`` EQUAL to existing ``lap`` -> ``target`` is NEVER
  changed, REGARDLESS of what the caller proposes for it — always keep
  ``existing.target``. This is what makes the race above safe:
  whichever of the two "start lap N+1" writers lands first establishes
  ``target`` permanently for that generation; the second writer's own
  write then finds ``proposed.lap == existing.lap`` (the first already
  bumped it) and falls into this ordinary same-lap path, where its
  own, different proposed ``target`` is simply discarded in favor of
  the already-persisted one.
* Proposed ``lap`` STRICTLY LESS than existing ``lap`` -> no-op exactly
  as today, trivially leaving ``target`` untouched (nothing changes on
  a no-op).
"""
from __future__ import annotations

import abc
import threading as _threading
from dataclasses import dataclass
from datetime import datetime
from typing import Collection, Optional

from core.timestamps import utc_now


@dataclass(frozen=True)
class EvidenceClassificationReconciliationCursor:
    #: Caller-chosen key — in practice always
    #: ``activation_boundary.isoformat()`` (see module docstring's own
    #: "Why cursor_key is activation_boundary.isoformat()" section).
    cursor_key: str
    #: Monotonically non-decreasing generation counter — see module
    #: docstring's own "lap" section. Compared BEFORE ``last_created_at``
    #: (lexicographic ``(lap, last_created_at)`` ordering): a genuinely
    #: NEWER lap always supersedes an older lap's position entirely,
    #: regardless of where its own ``last_created_at`` sits relative to
    #: the old lap's. The forward cursor never increments this itself
    #: (always proposes its own current value back unchanged); only the
    #: sweep cursor's own "start a new lap" decision ever proposes a
    #: strictly higher value.
    lap: int
    #: The ``created_at`` of the highest-ordered evidence row actually
    #: INSPECTED (never merely cursor-skipped) by the scan so far.
    last_created_at: datetime
    #: EVERY ``evidence_id`` actually inspected (never merely
    #: cursor-skipped) by any past call whose ``created_at`` was
    #: exactly ``last_created_at`` — a set-membership tie-break, never
    #: an ordering comparison (see module docstring's own "Why the
    #: tie-break is SET membership" section for why: cross-process
    #: UUIDv7 ordering is not guaranteed). A sorted tuple for a
    #: deterministic, hashable value on this frozen dataclass.
    last_evidence_ids: tuple[str, ...]
    #: The IMMUTABLE upper bound (``created_at`` value) for the CURRENT
    #: lap generation — see module docstring's own "target" section.
    #: Established exactly once per lap, at the moment that lap is
    #: proposed (a strictly-greater `lap` proposal); never changed by
    #: an equal-lap proposal, regardless of what that proposal supplies
    #: for it. Meaningful only for the sweep cursor — the forward
    #: cursor carries this field for schema uniformity only (mirrors
    #: how it already carries ``lap`` as a permanent non-event) and
    #: never meaningfully uses it.
    target: datetime
    created_at: datetime
    updated_at: datetime


def _resolve_cursor_advance(
    *,
    existing: Optional[EvidenceClassificationReconciliationCursor],
    proposed_lap: int,
    proposed_last_created_at: datetime,
    proposed_last_evidence_ids: Collection[str],
    proposed_target: datetime,
) -> tuple[int, datetime, tuple[str, ...], datetime, bool]:
    """The one, pure, shared merge-on-write decision every concrete
    `advance_cursor` implementation applies from inside its own row
    lock (see this module's own "Why advance_cursor merges instead of
    overwrites" AND "lap" docstring sections for the full reasoning) —
    never duplicated independently by each implementation.

    Ordering is now lexicographic on `(lap, last_created_at)`, `lap`
    compared FIRST — see module docstring's own "lap" section for why a
    plain `last_created_at` comparison alone is insufficient (a
    genuinely newer lap's own first, still-partial position must never
    be treated as "behind" an older, already-completed lap's final
    position).

    `target` (module docstring's own "target" section) is resolved by
    the SAME `lap` comparison, as an invariant this function itself
    enforces rather than merely relying on callers to propose it
    correctly: a strictly GREATER proposed `lap` introduces the
    proposal's own `target` (part of the same "accept wholesale"
    bundle); an EQUAL proposed `lap` NEVER changes `target` — always
    keeps `existing.target`, regardless of what is proposed — this is
    what makes two concurrent "start a new lap" proposals, each
    snapshotting a different target, resolve safely: whichever lands
    first establishes `target` for that generation permanently, and
    the second, now finding `proposed.lap == existing.lap`, falls into
    this same "never changed" rule.

    Returns `(lap, last_created_at, last_evidence_ids, target,
    changed)`: the cursor fields that should end up persisted, and
    whether that is actually DIFFERENT from `existing` (`existing=None`
    is always `changed=True` — there is nothing to compare against
    yet). `changed=False` tells the caller to skip a genuinely needless
    write and return `existing` completely unchanged (not even
    `updated_at` bumped) — the "a slower/stale-started caller's
    proposal never regresses a more-advanced persisted cursor" case,
    now on EITHER dimension.
    """
    proposed_ids = tuple(sorted(set(proposed_last_evidence_ids)))
    if existing is None:
        return proposed_lap, proposed_last_created_at, proposed_ids, proposed_target, True
    if proposed_lap > existing.lap:
        # A genuinely NEWER lap always supersedes the old lap's
        # position entirely — accept wholesale, regardless of where
        # proposed_last_created_at sits relative to existing's (see
        # module docstring's own "lap" section — this is the actual
        # fix for the permanent-stall class of bug). `target` is part
        # of this same wholesale acceptance — see "target" section:
        # this is the ONE path by which a new target value may ever be
        # introduced.
        return proposed_lap, proposed_last_created_at, proposed_ids, proposed_target, True
    if proposed_lap < existing.lap:
        # A stale caller proposing an older lap generation than what is
        # already persisted — never regress the lap counter either;
        # mirrors the existing created_at "less" case exactly. `target`
        # is trivially untouched (nothing changes on a no-op).
        return existing.lap, existing.last_created_at, existing.last_evidence_ids, existing.target, False
    # proposed_lap == existing.lap: fall through to EXACTLY the
    # pre-existing created_at-based comparison — unchanged, still safe
    # under concurrent same-lap writers (see module docstring's own
    # "Why advance_cursor merges instead of overwrites" section).
    # `target` is NEVER changed on this branch, regardless of what is
    # proposed for it — see module docstring's own "target" section;
    # this is the concurrency-safety invariant for a lap's own frozen
    # upper bound.
    if proposed_last_created_at > existing.last_created_at:
        return existing.lap, proposed_last_created_at, proposed_ids, existing.target, True
    if proposed_last_created_at == existing.last_created_at:
        merged_ids = tuple(sorted(set(existing.last_evidence_ids) | set(proposed_last_evidence_ids)))
        return (
            existing.lap,
            existing.last_created_at,
            merged_ids,
            existing.target,
            merged_ids != existing.last_evidence_ids,
        )
    # proposed_last_created_at < existing.last_created_at: another,
    # faster-or-earlier-starting caller already advanced this cursor_key
    # further within the SAME lap — never regress; no-op.
    return existing.lap, existing.last_created_at, existing.last_evidence_ids, existing.target, False


class EvidenceClassificationReconciliationCursorRepository(abc.ABC):
    @abc.abstractmethod
    def get_cursor(self, cursor_key: str) -> Optional[EvidenceClassificationReconciliationCursor]:
        """`None` if no cursor has ever been advanced for `cursor_key`
        yet — an ordinary, expected state for a fresh activation
        boundary's very first reconciliation call."""
        raise NotImplementedError

    @abc.abstractmethod
    def advance_cursor(
        self,
        cursor_key: str,
        *,
        lap: int,
        last_created_at: datetime,
        last_evidence_ids: Collection[str],
        target: datetime,
    ) -> EvidenceClassificationReconciliationCursor:
        """MERGE-ON-WRITE upsert (corrected this round — see module
        docstring's own "Why advance_cursor merges instead of
        overwrites" section; this is NO LONGER a blind overwrite):
        creates the row if it does not exist yet for `cursor_key`;
        otherwise, INSIDE the same lock/transaction that reads the
        current row, compares the caller's proposed `(lap,
        last_created_at)` against whatever is CURRENTLY persisted
        (never against whatever the caller itself last read, which may
        be stale) via :func:`_resolve_cursor_advance`, and:

        * proposed `lap` > persisted `lap` -> accepts the proposal's
          `(lap, last_created_at, last_evidence_ids, target)` WHOLESALE,
          unconditionally (a genuinely newer lap always supersedes an
          older lap's position — see module docstring's own "lap"
          section; this is what closes the permanent-stall class of
          bug, this round's correction);
        * proposed `lap` < persisted `lap` -> NO-OP, mirrors the
          `created_at` "less" case on this new dimension;
        * proposed `lap` == persisted `lap` -> falls through to EXACTLY
          the pre-existing `created_at`-based comparison, unchanged:
          proposed `created_at` > persisted -> replaces both fields;
          proposed == persisted -> UNIONS `last_evidence_ids` with
          whatever is already persisted (never replaces, never drops
          either side); proposed < persisted -> NO-OP, returns the
          EXISTING row completely unchanged (not even `updated_at`
          bumped) — never regresses a more-advanced persisted
          watermark. On this `lap == persisted lap` branch, `target` is
          NEVER changed, regardless of what the caller proposes for it
          — see module docstring's own "target" section for the full
          concurrency-safety reasoning.

        `lap` is meaningful for BOTH the forward and sweep cursor keys
        (see module docstring's own "lap" section): a caller advancing
        the forward cursor always proposes its own current persisted
        `lap` value back, unchanged (never invents or increments one);
        only the sweep cursor's own "start a new lap" decision ever
        proposes a strictly higher value than what is currently
        persisted. `target` (module docstring's own "target" section)
        follows the identical rule: a caller advancing the forward
        cursor always proposes its own current persisted `target` value
        back unchanged (a permanent non-event, mirroring `lap`); the
        sweep cursor snapshots a fresh `target` ONLY at the exact
        moment it proposes a strictly higher `lap` (starting a new lap),
        and otherwise proposes its own current persisted `target` value
        back unchanged too (continuing the SAME lap) — though this
        repository enforces the "never changed on an equal-lap
        proposal" half of that rule itself, regardless of what the
        caller proposes.

        The caller's own `last_evidence_ids` must be the FULL set of
        ids IT inspected at ITS OWN proposed `last_created_at` (the
        union of any prior call's ids at that same timestamp plus
        whatever was newly inspected this call, when the watermark did
        not move past it, exactly as before) — this repository's own
        merge, above, is a SEPARATE, additional union against whatever
        a DIFFERENT concurrent/earlier caller may have persisted in the
        meantime, not a substitute for the caller doing its own
        bookkeeping correctly."""
        raise NotImplementedError


class InMemoryEvidenceClassificationReconciliationCursorRepository(
    EvidenceClassificationReconciliationCursorRepository
):
    """Narrow in-memory reference implementation. `RLock`-guarded,
    mirroring every other in-memory repository in this codebase that
    may see genuine concurrent HTTP-driven callers within one process
    (e.g. `services.evidence.classification_job
    .InMemoryEvidenceClassificationJobRepository`)."""

    def __init__(self) -> None:
        self._by_key: dict[str, EvidenceClassificationReconciliationCursor] = {}
        self._lock = _threading.RLock()

    def get_cursor(self, cursor_key: str) -> Optional[EvidenceClassificationReconciliationCursor]:
        with self._lock:
            return self._by_key.get(cursor_key)

    def advance_cursor(
        self,
        cursor_key: str,
        *,
        lap: int,
        last_created_at: datetime,
        last_evidence_ids: Collection[str],
        target: datetime,
    ) -> EvidenceClassificationReconciliationCursor:
        with self._lock:
            existing = self._by_key.get(cursor_key)
            merged_lap, merged_created_at, merged_ids, merged_target, changed = _resolve_cursor_advance(
                existing=existing,
                proposed_lap=lap,
                proposed_last_created_at=last_created_at,
                proposed_last_evidence_ids=last_evidence_ids,
                proposed_target=target,
            )
            if not changed:
                # existing is guaranteed non-None here: changed is only
                # ever False when existing is not None (see
                # _resolve_cursor_advance) — never regress it, not even
                # updated_at.
                return existing  # type: ignore[return-value]
            now = utc_now()
            updated = EvidenceClassificationReconciliationCursor(
                cursor_key=cursor_key,
                lap=merged_lap,
                last_created_at=merged_created_at,
                last_evidence_ids=merged_ids,
                target=merged_target,
                created_at=existing.created_at if existing is not None else now,
                updated_at=now,
            )
            self._by_key[cursor_key] = updated
            return updated
