"""initial schema

Revision ID: 13a9ed820cfd
Revises: 
Create Date: 2026-09-12 18:36:13.501268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13a9ed820cfd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('audit_event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('correlation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('causation_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('audit_event_id')
    )
    op.create_index('ix_audit_events_correlation', 'audit_events', ['correlation_id'], unique=False)
    op.create_index('ix_audit_events_subject', 'audit_events', ['subject_type', 'subject_id'], unique=False)
    op.create_table('governed_entities',
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('sources',
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('external_source_ref', sa.String(), nullable=True),
    sa.Column('governed_entity_hint', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('evidence_items',
    sa.Column('evidence_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('storage_reference', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['governed_entities.entity_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('external_references',
    sa.Column('external_reference_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('canonical_object_type', sa.String(), nullable=False),
    sa.Column('canonical_object_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('external_reference_id'),
    sa.UniqueConstraint('provider', 'source_id', 'resource_type', 'external_id', name='uq_external_references_tuple')
    )
    op.create_table('provenance',
    sa.Column('provenance_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('evidence_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('transform_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.evidence_id'], ),
    sa.PrimaryKeyConstraint('provenance_id')
    )
    op.create_index('ix_provenance_subject', 'provenance', ['subject_type', 'subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provenance_subject', table_name='provenance')
    op.drop_table('provenance')
    op.drop_table('external_references')
    op.drop_table('evidence_items')
    op.drop_table('sources')
    op.drop_table('governed_entities')
    op.drop_index('ix_audit_events_subject', table_name='audit_events')
    op.drop_index('ix_audit_events_correlation', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
